### ISSUE TITLE
data missing

### ISSUE THREAD

**Issue by qianwTS** [orlandoandradeb/Four-step-model-demand-in-python#1]
hi!
i was trying to learn your python code in 4-steps demand  modeling but couldn't run through your code. there is no zone shape at the very beginning of data preparation. and the road folder is empty. 
do you happen to have a english version

**Comment by orlandombaa** [comment]
Hello @qianwTS  

Some data are not included in the folder becase the size of the file. However, you can generated directly in the  code , the road file is generated automatically within the same code (it is dowload using the library of  osmnx ) you just need the mask.
